import fs from "node:fs"
import path from "node:path"

export function createDirectories(root) {
    fs.mkdirSync(root, { recursive: true })
    fs.mkdirSync(path.join(root, "src"))
}

export function writePackageJson(root, packageName, repoUrl = "") {
    let homepage = undefined
    let bugs = undefined

    if (repoUrl) {
        const baseUrl = repoUrl.replace(/\.git$/, "")

        if (repoUrl.includes("github.com") || repoUrl.includes("gitlab.com")) {
            homepage = `${baseUrl}#readme`
            bugs = {
                url: `${baseUrl}/issues`
            }
        }
    }

    const content = {
        name: packageName,
        version: "0.1.0",
        type: "commonjs",
        repository: repoUrl ? {
            type: "git",
            url: repoUrl
        } : undefined,
        homepage,
        bugs,
        main: "./dist/index.js",
        module: "./dist/index.js",
        types: "./dist/index.d.ts",
        files: [
            "dist/*",
            "!/**/__tests__"
        ],
        scripts: {
            build: "tsc",
            dev: "ts-node ./src/index.ts",
            format: "prettier --write \"src/**/*.ts\"",
            lint: "eslint \"src/**/*.ts\" --fix"
        },
        publishConfig: {
            access: "public"
        },
        keywords: [
            "marcuth"
        ],
        author: "Marcuth",
        license: "MIT"
    }

    fs.writeFileSync(
        path.join(root, "package.json"),
        JSON.stringify(content, null, 2)
    )
}

export function writeTsConfig(root) {
    const content = {
        "compilerOptions": {
            "target": "es2019",
            "lib": ["ES2015"],
            "module": "NodeNext",
            "esModuleInterop": true,
            "forceConsistentCasingInFileNames": true,
            "strict": true,
            "skipLibCheck": true,
            "outDir": "./dist",
            "rootDir": "./src",
            "declaration": true,
            "declarationMap": false,
        },
        "include": ["src"],
        "exclude": ["node_modules", "dist"]
    }

    fs.writeFileSync(
        path.join(root, "tsconfig.json"),
        JSON.stringify(content, null, 2)
    )
}

export function writeSourceFile(root, projectDir) {
    const content = `function main() {
    console.log("Hello from ${projectDir}")
}

main()
`

    fs.writeFileSync(
        path.join(root, "src/index.ts"),
        content
    )
}

export function writeLicenseFile(root) {
    const currentYear = new Date().getFullYear()

    const content = `MIT License

Copyright (c) ${currentYear} Marcuth

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.`

    fs.writeFileSync(
        path.join(root, "LICENSE"),
        content
    )
}

export function writeGitignoreFile(root) {
    const content = `# Created by https://www.toptal.com/developers/gitignore/api/node
# Edit at https://www.toptal.com/developers/gitignore?templates=node

### Node ###
# Logs
dist/
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
lerna-debug.log*
.pnpm-debug.log*

# Diagnostic reports (https://nodejs.org/api/report.html)
report.[0-9]*.[0-9]*.[0-9]*.[0-9]*.json

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage
*.lcov

# nyc test coverage
.nyc_output

# Grunt intermediate storage (https://gruntjs.com/creating-plugins#storing-task-files)
.grunt

# Bower dependency directory (https://bower.io/)
bower_components

# node-waf configuration
.lock-wscript

# Compiled binary addons (https://nodejs.org/api/addons.html)
build/Release

# Dependency directories
node_modules/
jspm_packages/

# Snowpack dependency directory (https://snowpack.dev/)
web_modules/

# TypeScript cache
*.tsbuildinfo

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Optional stylelint cache
.stylelintcache

# Microbundle cache
.rpt2_cache/
.rts2_cache_cjs/
.rts2_cache_es/
.rts2_cache_umd/

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# dotenv environment variable files
.env
.env.development.local
.env.test.local
.env.production.local
.env.local

# parcel-bundler cache (https://parceljs.org/)
.cache
.parcel-cache

# Next.js build output
.next
out

# Nuxt.js build / generate output
.nuxt
dist

# Gatsby files
.cache/
# Comment in the public line in if your project uses Gatsby and not Next.js
# https://nextjs.org/blog/next-9-1#public-directory-support
# public

# vuepress build output
.vuepress/dist

# vuepress v2.x temp and cache directory
.temp

# Docusaurus cache and generated files
.docusaurus

# Serverless directories
.serverless/

# FuseBox cache
.fusebox/

# DynamoDB Local files
.dynamodb/

# TernJS port file
.tern-port

# Stores VSCode versions used for testing VSCode extensions
.vscode-test

# yarn v2
.yarn/cache
.yarn/unplugged
.yarn/build-state.yml
.yarn/install-state.gz
.pnp.*

### Node Patch ###
# Serverless Webpack directories
.webpack/

# Optional stylelint cache

# SvelteKit build / generate output
.svelte-kit

# End of https://www.toptal.com/developers/gitignore/api/node`

    fs.writeFileSync(
        path.join(root, ".gitignore"),
        content
    )
}

export function writeGitAttributes(root) {
    const content = `*.js linguist-generated=true
*.d.ts linguist-generated=true`

    fs.writeFileSync(
        path.join(root, ".gitattributes"),
        content
    )
}

export function createNpmIgnore(root) {
    const content = `src/
tsconfig.json`

    fs.writeFileSync(
        path.join(root, ".npmignore"),
        content
    )
}

export function createReadme(root, packageName) {
    const content = `# ${packageName}`

    fs.writeFileSync(
        path.join(root, "README.md"),
        content
    )
}

export function createEsLintRcConfig(root) {
    const content = {
        "extends": [
            "plugin:prettier/recommended"
        ],
        "plugins": [
            "prettier",
            "unused-imports"
        ],
        "rules": {
            "prettier/prettier": "error",
            "no-unused-vars": "off",
            "unused-imports/no-unused-imports": "error",
            "unused-imports/no-unused-vars": [
                "warn",
                { "vars": "all", "varsIgnorePattern": "^_", "args": "after-used", "argsIgnorePattern": "^_" }
            ]
        }
    }

    fs.writeFileSync(
        path.join(root, ".eslintrc.json"),
        JSON.stringify(content, null, 4)
    )
}

export function createPrettierConfig(root) {
    const content = `module.exports = {
    "semi": false,
    "singleQuote": false,
    "tabWidth": 4,
    "useTabs": false,
    "importTypeOrder": ["NPMPackages", "localImports"],
    "newlineBetweenTypes": true,
    "sortingMethod": "lineLength",
    "plugins": ["./node_modules/prettier-plugin-sort-imports/dist/index.js"],
    "endOfLine": "auto",
    "printWidth": 120
}`

    fs.writeFileSync(
        path.join(root, ".prettierrc.js"),
        content
    )
}
